name: mybinder_test
channels:
  - defaults
  - conda-forge
  - conda-forge/label/broken
dependencies:
  - ca-certificates
  - certifi
  - openssl
  - pip
  - python
  - setuptools
  - sqlite
  - tzdata
  - wheel
  - pip:
    - ansitable
    - anyio
    - argon2-cffi
    - argon2-cffi-bindings
    - asteval
    - asttokens
    - attrs
    - babel
    - backcall
    - beautifulsoup4
    - bleach
    - cffi
    - charset-normalizer
    - colorama
    - colored
    - cycler
    - debugpy
    - decorator
    - defusedxml
    - deprecation
    - entrypoints
    - executing
    - fastjsonschema
    - fonttools
    - future
    - idna
    - importlib-metadata
    - ipykernel
    - ipython
    - ipython-genutils
    - ipywidgets
    - jedi
    - jinja2
    - json5
    - jsonschema
    - jupyter-client
    - jupyter-core
    - jupyter-packaging
    - jupyter-server
    - jupyterlab
    - jupyterlab-pygments
    - jupyterlab-server
    - jupyterlab-widgets
    - kiwisolver
    - lmfit
    - markupsafe
    - matplotlib
    - matplotlib-inline
    - mistune
    - nbclassic
    - nbclient
    - nbconvert
    - nbformat
    - nest-asyncio
    - notebook
    - notebook-shim
    - numpy
    - numpy-stl
    - open3d
    - packaging
    - pandocfilters
    - parso
    - pickleshare
    - pillow
    - prometheus-client
    - prompt-toolkit
    - psutil
    - pure-eval
    - pycparser
    - pygments
    - pyparsing
    - pyrsistent
    - python-dateutil
    - python-utils
    - pytz
    - pywin32
    - pywinpty
    - pyzmq
    - requests
    - scipy
    - send2trash
    - six
    - sniffio
    - soupsieve
    - spatialmath-python
    - stack-data
    - terminado
    - tinycss2
    - tomlkit
    - tornado
    - traitlets
    - uncertainties
    - urllib3
    - wcwidth
    - webencodings
    - websocket-client
    - widgetsnbextension
    - zipp
