name: conda_test
channels:
  - defaults
dependencies:
  - ca-certificates
  - certifi
  - openssl
  - pip
  - python
  - setuptools
  - sqlite
  - tzdata
  - vc
  - vs2015_runtime
  - wheel
  - wincertstore